spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://chavezsantiago480:chavezsantiagoMongo480@cluster0.gc6john.mongodb.net/ecomerce?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:ecomerce}
server.port=${PORT:8080}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5176,http://127.0.0.1:5176,http://localhost:3000,http://localhost:80,https://*.vercel.app,https://*.onrender.com,*}
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG