spring.data.mongodb.uri=mongodb+srv://chavezsantiago480:chavezsantiagoMongo480@cluster0.gc6john.mongodb.net/ecomerce?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=ecomerce
server.port=8080
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG